apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plugin-demo
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    path: ./
    plugin:
      env:
      - name: FOO
        value: bar
    repoURL: https://github.com/akuity/mta
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true